### ISSUE TITLE
[Feature Request] Allow For Searching Unknown Values (Health Bars Etc)

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [zorgiepoo/Bit-Slicer#25] opened 2015-12-26 08:45 UTC
now i can mod most games with this but when it comes to a health bar or a bar type value. no one knows the exact value.

now is there a current method to search for an unknown value meaning do an initial scan for every single value in the memory on the attached process.

then do a scan based on these:
Value has increased
Value has decreased
Value is unchanged (like you haven't done anything in the game yet to change the value good for cleaning out constant changing values)

i want to be able to do the same thing here: https://youtu.be/r1V7RQKPuIs?t=134
but with BitSlicer

**Comment by zorgiepoo** [comment] 2015-12-26 15:24
Duplicate of #20 

Scanning all data types at once is not possible but should be reported as a separate issue

**Comment by JPaulMora** [comment] 2016-10-13 18:40
Yes, please add this feature! BitSlicer is awesome!

**Comment by zorgiepoo** [comment] 2016-10-13 21:05
@JPaulMora Please take a look at the [wiki page](https://github.com/zorgiepoo/Bit-Slicer/wiki/Storing-All-Values) for how to simulate this (re: #20).

**Comment by JPaulMora** [comment] 2016-10-14 01:29
Wow! Thanks! looks like I skipped that part of the wiki.

**Comment by zorgiepoo** [comment] 2016-10-14 13:00
> AFAIK $StoredValue keeps only the first "Scan" is that the case?

Nope. It refers to the value the last time values were stored by the user. You could eg: store values after every scan, or only store values once and do several scans as the example on the wiki page shows.

**Closed** 2017-02-08 00:03 UTC
